# Generated by Django 2.0.1 on 2018-01-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20180122_1954'),
        ('cms', '0003_auto_20180123_1051'),
    ]

    operations = [
    ]
