# Generated by Django 2.0.1 on 2018-01-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_auto_20180123_1149"),
        ("cms", "0004_merge_20180123_1159"),
    ]

    operations = []
