# Generated by Django 2.0.1 on 2018-01-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20180124_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='media_original',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang'),
        ),
        migrations.AddField(
            model_name='reportfragment',
            name='media_original',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang'),
        ),
        migrations.AlterField(
            model_name='report',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Verarbeitet'),
        ),
        migrations.AlterField(
            model_name='reportfragment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Verarbeitet'),
        ),
    ]
