# Generated by Django 2.0.1 on 2018-01-25 11:50

import cms.models.wiki
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20180125_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_original', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang')),
                ('media_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Credit')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Verarbeitet')),
                ('name', models.CharField(max_length=200, verbose_name='Einzelheit')),
                ('follow_up_at', models.DateTimeField(default=cms.models.wiki.default_follow_up_at, verbose_name='Wiedervorlage')),
                ('text', models.CharField(max_length=640, verbose_name='Intro-Text')),
                ('genres', models.ManyToManyField(related_name='wikis', to='cms.Genre', verbose_name='Genre')),
                ('tags', models.ManyToManyField(related_name='wikis', to='cms.ReportTag')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wikis', to='cms.Topic', verbose_name='Thema')),
            ],
            options={
                'verbose_name': 'Einzelheit',
                'verbose_name_plural': 'Einzelheiten',
            },
        ),
        migrations.CreateModel(
            name='WikiFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_original', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang')),
                ('media_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Credit')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Verarbeitet')),
                ('question', models.CharField(blank=True, max_length=20, null=True, verbose_name='Frage')),
                ('text', models.CharField(max_length=640, verbose_name='Text')),
                ('link_wiki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='cms.Wiki')),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', related_query_name='fragment', to='cms.Wiki')),
            ],
            options={
                'verbose_name': 'Einzelheiten-Fragment',
                'verbose_name_plural': 'Einzelheiten-Fragmente',
            },
        ),
    ]
