# Generated by Django 2.0.1 on 2018-01-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0015_auto_20180125_1420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="items",
                to="cms.ReportTag",
                verbose_name="Tags",
            ),
        ),
    ]
