# Generated by Django 2.0.1 on 2018-01-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0016_auto_20180125_1449"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faqfragment",
            options={
                "ordering": ("id",),
                "verbose_name": "FAQ-Fragment",
                "verbose_name_plural": "FAQ-Fragmente",
            },
        ),
        migrations.AlterModelOptions(
            name="reportfragment",
            options={
                "ordering": ("id",),
                "verbose_name": "Meldungs-Fragment",
                "verbose_name_plural": "Meldungs-Fragmente",
            },
        ),
        migrations.AlterModelOptions(
            name="wikifragment",
            options={
                "ordering": ("id",),
                "verbose_name": "Einzelheiten-Fragment",
                "verbose_name_plural": "Einzelheiten-Fragmente",
            },
        ),
    ]
