# Generated by Django 2.0.1 on 2018-01-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20180125_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqfragment',
            options={'ordering': ('id',), 'verbose_name': 'FAQ-Fragment', 'verbose_name_plural': 'FAQ-Fragmente'},
        ),
        migrations.AlterModelOptions(
            name='reportfragment',
            options={'ordering': ('id',), 'verbose_name': 'Meldungs-Fragment', 'verbose_name_plural': 'Meldungs-Fragmente'},
        ),
        migrations.AlterModelOptions(
            name='wikifragment',
            options={'ordering': ('id',), 'verbose_name': 'Einzelheiten-Fragment', 'verbose_name_plural': 'Einzelheiten-Fragmente'},
        ),
        migrations.AlterField(
            model_name='report',
            name='genres',
            field=models.ManyToManyField(related_name='report', to='cms.Genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='report',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='report', to='cms.ReportTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='report',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='cms.Topic', verbose_name='Thema'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='genres',
            field=models.ManyToManyField(related_name='wiki', to='cms.Genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='wiki', to='cms.ReportTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki', to='cms.Topic', verbose_name='Thema'),
        ),
    ]
