# Generated by Django 2.0.2 on 2018-03-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20180228_1057'),
        ('cms', '0019_subscription'),
    ]

    operations = [
    ]
