# Generated by Django 2.0.3 on 2018-03-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0017_auto_20180125_2031"),
        ("cms", "0022_push_delivered_date"),
    ]

    operations = []
