# Generated by Django 2.0.5 on 2018-06-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_merge_20180321_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
