# Generated by Django 2.0.3 on 2018-07-17 14:13

from django.db import migrations, models
import django.utils.timezone

def migrate_dates(apps, schema_editor):
    Report = apps.get_model("cms", "Report")

    for report in Report.objects.all():

        report.modified = report.created

        if report.published:
            report.published_date = report.created

        report.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_auto_20180627_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bearbeitet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='published_date',
            field=models.DateTimeField(null=True, verbose_name='Veröffentlicht'),
        ),
        migrations.RunPython(migrate_dates),
    ]
