# Generated by Django 2.0.3 on 2018-09-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_auto_20180719_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='media_alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternativ-Text'),
        ),
        migrations.AddField(
            model_name='faqfragment',
            name='media_alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternativ-Text'),
        ),
        migrations.AddField(
            model_name='push',
            name='media_alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternativ-Text'),
        ),
        migrations.AddField(
            model_name='report',
            name='media_alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternativ-Text'),
        ),
        migrations.AddField(
            model_name='reportfragment',
            name='media_alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternativ-Text'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='media_alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternativ-Text'),
        ),
        migrations.AddField(
            model_name='wikifragment',
            name='media_alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternativ-Text'),
        ),
    ]
