# Generated by Django 2.0.7 on 2018-09-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_auto_20180719_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='author',
            field=models.CharField(default='Susanne Schwarzbach', max_length=200, verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
