# Generated by Django 2.0.7 on 2018-09-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0030_auto_20180903_1129"),
        ("cms", "0030_report_author"),
    ]

    operations = []
