# Generated by Django 2.0.7 on 2018-09-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0031_merge_20180904_1202"),
        ("cms", "0035_auto_20180905_1457"),
    ]

    operations = []
