# Generated by Django 2.0.8 on 2019-09-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_auto_20180907_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='link',
            field=models.URLField(null=True, verbose_name='DeepLink'),
        ),
    ]
