# Generated by Django 2.2.5 on 2019-09-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0039_report_link"),
        ("cms", "0039_auto_20190919_1036"),
    ]

    operations = []
