# Generated by Django 2.2.10 on 2020-02-12 14:57

from django.db import migrations, models


def migrate_push_delivered(apps, schema_editor):
    Push = apps.get_model("cms", "Push")

    for push in Push.objects.all():
        if push.delivered:
            push.delivered_fb = 'sent'
            push.save()


def migrate_report_delivered(apps, schema_editor):
    Report = apps.get_model("cms", "Report")

    for report in Report.objects.all():
        if report.delivered:
            report.delivered_fb = 'sent'
            report.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0054_auto_20200212_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='push',
            old_name='delivered_date',
            new_name='delivered_date_fb'
        ),
        migrations.AlterField(
            model_name='push',
            name='delivered_date_fb',
            field=models.DateTimeField(null=True, verbose_name='Versand-Datum Facebook'),
        ),
        migrations.AddField(
            model_name='push',
            name='delivered_fb',
            field=models.CharField(choices=[('not_sent', 'nicht gesendet'), ('sending', 'wird gesendet'), ('sent', 'gesendet')], default='not_sent', max_length=20, verbose_name='Facebook'),
        ),
        migrations.RunPython(migrate_push_delivered),
        migrations.RemoveField(
            model_name='push',
            name='delivered',
        ),
        migrations.AddField(
            model_name='report',
            name='delivered_fb',
            field=models.CharField(choices=[('not_sent', 'nicht gesendet'), ('sending', 'wird gesendet'), ('sent', 'gesendet')], default='not_sent', max_length=20, verbose_name='Breaking: Facebook'),
        ),
        migrations.RunPython(migrate_report_delivered),
        migrations.RemoveField(
            model_name='report',
            name='delivered',
        ),
    ]
