# Generated by Django 3.0.4 on 2020-03-10 13:31

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


def migrate_attachment(apps, schema_editor):
    models = ['FAQ', 'FAQFragment', 'Push', 'Report', 'ReportFragment', 'ReportQuiz', 'Wiki', 'WikiFragment']
    Attachment = apps.get_model("cms", "Attachment")
    for model_name in models:
        Model = apps.get_model("cms", model_name)

        for obj in Model.objects.all():
            if not obj.media or str(obj.media) == '':
                continue

            attachment = Attachment(
                original=obj.media_original,
                title=obj.media_alt or 'Kein Titel',
                credit=obj.media_note,
                processed=obj.media,
            )
            attachment.save()
            obj.attachment = attachment
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0057_auto_20200213_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Titel')),
                ('original', s3direct.fields.S3DirectField(blank=True, help_text='Zulässige Dateiformate: *.jpg, *.jpeg, *.png, *.mp3, *.mp4, *.gif', null=True, verbose_name='Medien-Anhang')),
                ('credit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Credit')),
                ('processed', models.FileField(blank=True, null=True, upload_to='', verbose_name='Verarbeitet')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='cms.Attachment'),
        ),
        migrations.AddField(
            model_name='faqfragment',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='cms.Attachment'),
        ),
        migrations.AddField(
            model_name='push',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='cms.Attachment'),
        ),
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='cms.Attachment'),
        ),
        migrations.AddField(
            model_name='reportfragment',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='cms.Attachment'),
        ),
        migrations.AddField(
            model_name='reportquiz',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='cms.Attachment'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='cms.Attachment'),
        ),
        migrations.AddField(
            model_name='wikifragment',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='cms.Attachment'),
        ),
        migrations.RunPython(migrate_attachment),
        migrations.RemoveField(
            model_name='faq',
            name='media',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='media_alt',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='media_note',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='media_original',
        ),
        migrations.RemoveField(
            model_name='faqfragment',
            name='media',
        ),
        migrations.RemoveField(
            model_name='faqfragment',
            name='media_alt',
        ),
        migrations.RemoveField(
            model_name='faqfragment',
            name='media_note',
        ),
        migrations.RemoveField(
            model_name='faqfragment',
            name='media_original',
        ),
        migrations.RemoveField(
            model_name='push',
            name='media',
        ),
        migrations.RemoveField(
            model_name='push',
            name='media_alt',
        ),
        migrations.RemoveField(
            model_name='push',
            name='media_note',
        ),
        migrations.RemoveField(
            model_name='push',
            name='media_original',
        ),
        migrations.RemoveField(
            model_name='report',
            name='media',
        ),
        migrations.RemoveField(
            model_name='report',
            name='media_alt',
        ),
        migrations.RemoveField(
            model_name='report',
            name='media_note',
        ),
        migrations.RemoveField(
            model_name='report',
            name='media_original',
        ),
        migrations.RemoveField(
            model_name='reportfragment',
            name='media',
        ),
        migrations.RemoveField(
            model_name='reportfragment',
            name='media_alt',
        ),
        migrations.RemoveField(
            model_name='reportfragment',
            name='media_note',
        ),
        migrations.RemoveField(
            model_name='reportfragment',
            name='media_original',
        ),
        migrations.RemoveField(
            model_name='reportquiz',
            name='media',
        ),
        migrations.RemoveField(
            model_name='reportquiz',
            name='media_alt',
        ),
        migrations.RemoveField(
            model_name='reportquiz',
            name='media_note',
        ),
        migrations.RemoveField(
            model_name='reportquiz',
            name='media_original',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='media',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='media_alt',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='media_note',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='media_original',
        ),
        migrations.RemoveField(
            model_name='wikifragment',
            name='media',
        ),
        migrations.RemoveField(
            model_name='wikifragment',
            name='media_alt',
        ),
        migrations.RemoveField(
            model_name='wikifragment',
            name='media_note',
        ),
        migrations.RemoveField(
            model_name='wikifragment',
            name='media_original',
        ),
    ]
