# Generated by Django 3.0.4 on 2020-03-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0058_auto_20200310_1331"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "verbose_name": "Medien-Anhang",
                "verbose_name_plural": "Medien-Anhänge",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="tgid",
            field=models.CharField(
                blank=True,
                help_text="Sende #ich an den Bot, und trage die Zahl hier ein, um Meldungen und Pushes testen zu können.",
                max_length=256,
                null=True,
                verbose_name="Telegram-ID",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to="cms.Attachment",
                verbose_name="Medien-Anhang",
            ),
        ),
        migrations.AlterField(
            model_name="faqfragment",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to="cms.Attachment",
                verbose_name="Medien-Anhang",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="psid",
            field=models.CharField(
                blank=True,
                help_text="Sende #ich an den Bot, und trage die Zahl hier ein, um Meldungen und Pushes testen zu können.",
                max_length=256,
                null=True,
                verbose_name="Facebook-ID",
            ),
        ),
        migrations.AlterField(
            model_name="push",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to="cms.Attachment",
                verbose_name="Medien-Anhang",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to="cms.Attachment",
                verbose_name="Medien-Anhang",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Nach diesen Worten können Nutzer:innen im Bot fragen.",
                related_name="report",
                to="cms.ReportTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="reportfragment",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to="cms.Attachment",
                verbose_name="Medien-Anhang",
            ),
        ),
        migrations.AlterField(
            model_name="reportquiz",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to="cms.Attachment",
                verbose_name="Medien-Anhang",
            ),
        ),
        migrations.AlterField(
            model_name="wiki",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to="cms.Attachment",
                verbose_name="Medien-Anhang",
            ),
        ),
        migrations.AlterField(
            model_name="wiki",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Nach diesen Worten können Nutzer:innen im Bot fragen.",
                related_name="wiki",
                to="cms.ReportTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="wikifragment",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to="cms.Attachment",
                verbose_name="Medien-Anhang",
            ),
        ),
    ]
