# Generated by Django 3.0.4 on 2020-03-19 11:25

from django.db import migrations, models
import django.db.models.deletion


def set_default_breaking_subtype(apps, schema_editor):
    Report = apps.get_model("cms", "Report")
    Subtype = apps.get_model("cms", "Subtype")

    default_subtype = Subtype(emoji='🚨', title='Eilmeldung', type='breaking')
    default_subtype.save()

    for report in Report.objects.filter(type='breaking'):
        report.subtype = default_subtype
        report.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0061_auto_20200317_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtype',
            name='type',
            field=models.CharField(choices=[('regular', '📰 Reguläre Meldung'), ('last', '🎨 Letzte Meldung'), ('breaking', '🚨 Breaking')], default='last', help_text='Hier kannst du wählen, zu welchem Meldungstyp dieser Subtyp gehört.', max_length=20, verbose_name='Meldungstyp'),
        ),
        migrations.AlterField(
            model_name='push',
            name='link',
            field=models.URLField(blank=True, default=None, help_text='Der PromoLink wird am Ende am Ende des Push-Outro angehangen. Der Button-Text lautet: "🔗 {Schlagwort PromoLink}".Damit bietet das Outro die Möglichkeit der Cross-Promo von WDR-Inhalten.', max_length=500, null=True, verbose_name='PromoLink'),
        ),
        migrations.AlterField(
            model_name='push',
            name='link_name',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Schlagwort PromoLink'),
        ),
        migrations.AlterField(
            model_name='report',
            name='subtype',
            field=models.ForeignKey(blank=True, help_text='Derzeit nur relevant für Meldungen vom Typ "🎨 Letzte Meldung" und "🚨 Breaking".', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', related_query_name='report', to='cms.Subtype', verbose_name='Subtyp'),
        ),
        migrations.RunPython(set_default_breaking_subtype),
    ]
