# Generated by Django 3.0.4 on 2020-04-29 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0061_auto_20200317_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='link',
            field=models.URLField(blank=True, default=None, help_text='Der PromoLink wird am Ende am Ende des Push-Outro angehangen. Der Button-Text lautet: "🔗 {Schlagwort PromoLink}".Damit bietet das Outro die Möglichkeit der Cross-Promo von WDR-Inhalten.', max_length=500, null=True, verbose_name='PromoLink'),
        ),
        migrations.AlterField(
            model_name='push',
            name='link_name',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Schlagwort PromoLink'),
        ),
        migrations.AlterField(
            model_name='report',
            name='subtype',
            field=models.ForeignKey(blank=True, help_text='Derzeit nur relevant für Meldungen vom Typ "🎨 Letzte Meldung".', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', related_query_name='report', to='cms.Subtype', verbose_name='Subtyp'),
        ),
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=models.CharField(blank=True, help_text='Dieser Text wird bei Telegram als Meldungstext zusammen mit der Überschrift ausgespielt.', max_length=900, null=True, verbose_name='Telegram-Text'),
        ),
    ]
