# Generated by Django 3.0.4 on 2020-04-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0062_auto_20200429_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='push',
            name='headline',
        ),
    ]
