# Generated by Django 3.0.5 on 2020-05-27 09:32

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0065_auto_20200526_1226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="original",
            field=s3direct.fields.S3DirectField(
                help_text="Zulässige Dateiformate: *.jpg, *.jpeg, *.png, *.mp3, *.mp4, *.gif",
                verbose_name="Medien-Anhang",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="processed",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="",
                verbose_name="Verarbeitet",
            ),
        ),
        migrations.AlterField(
            model_name="push",
            name="link",
            field=models.URLField(
                blank=True,
                default=None,
                help_text='Der Link wird am Ende am Ende des Push-Outro angehangen. Der Button-Text lautet: "🔗 {Link-Button-Text}".Damit bietet das Outro u.a. die Möglichkeit der Cross-Promo von WDR-Inhalten.',
                max_length=500,
                null=True,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="push",
            name="link_name",
            field=models.CharField(
                blank=True, max_length=17, null=True, verbose_name="Link-Button-Text"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="link",
            field=models.URLField(
                blank=True,
                default=None,
                help_text='Der Link wird am Ende einer Meldung (FB-Messenger und Letzte Meldung) mit dem Button-Text "MEHR 🌍" ausgespielt, respektive als Hyperlink hinter dem Schlagwort-Text nach dem Telegram-Text.',
                max_length=500,
                null=True,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="short_headline",
            field=models.CharField(
                help_text="Hinter diesem Schlagwort wird in TG der Deeplink gesetzt. Außerdem ist dies der Text, der auf dem Auswahl-Button für diese Nachricht angezeigt in FB angezeigt wird.",
                max_length=17,
                verbose_name="Link-/Button-Text",
            ),
        ),
    ]
