# Generated by Django 3.1.3 on 2020-11-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0069_auto_20201118_1109"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSent",
            fields=[
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_sent",
                        related_query_name="notification_sent",
                        serialize=False,
                        to="cms.report",
                        verbose_name="Meldung",
                    ),
                ),
                ("fb", models.BooleanField(verbose_name="Facebook")),
                ("tg", models.BooleanField(verbose_name="Telegram")),
                ("morning", models.BooleanField(verbose_name="☕ Morgen")),
                ("evening", models.BooleanField(verbose_name="🌙 Abend")),
                ("breaking", models.BooleanField(verbose_name="🚨 Breaking")),
            ],
            options={
                "verbose_name": "Gesendete Benachrichtigung",
                "verbose_name_plural": "Gesendete Benachrichtigungen",
            },
        ),
    ]
