# Generated by Django 3.1.5 on 2021-01-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0072_auto_20210126_1314"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teaser",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Meldung",
                "verbose_name_plural": "Meldungen",
            },
        ),
        migrations.AddField(
            model_name="teaser",
            name="ordering",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Sortierung"
            ),
        ),
    ]
