# Generated by Django 3.1.5 on 2021-01-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0073_auto_20210126_1334"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promo",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Promo",
                "verbose_name_plural": "Promos",
            },
        ),
        migrations.AddField(
            model_name="promo",
            name="ordering",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Sortierung"
            ),
        ),
    ]
