# Generated by Django 3.1.5 on 2021-01-27 09:40

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0074_auto_20210126_1446"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="original",
            field=s3direct.fields.S3DirectField(
                help_text="Zulässige Dateiformate: *.jpg, *.jpeg, *.png, *.gif",
                verbose_name="Medien-Anhang",
            ),
        ),
    ]
